version: "3"
services:
  manager:
    build: manager
    environment:
      PORT: 8080
      DATABASE_URL: postgres://ztp:ztp@db:5432/ztp?sslmode=disable
      NODE_MODULE: pg
    ports:
      - 8080
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: ztp
      POSTGRES_USER: ztp
      POSTGRES_PASSWORD: ztp
