version: "3"
services:
  manager:
    image: kstm/ztp:manager
#   build: manager
    environment:
      PORT: 8080
      SOCKET: /run/manager.sock
      DATABASE_URL: postgres://ztp:ztp@db:5432/ztp?sslmode=disable
      NODE_MODULE: pg
      STORAGE_URL: http://storage:3000
    ports:
      - "${MANAGER_PORT}:8080"
    volumes:
      - ./tmp/run:/run
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: ztp
      POSTGRES_USER: ztp
      POSTGRES_PASSWORD: ztp
  dhcp:
    image: kstm/ztp:dhcp
#   build: dhcp
    network_mode: host
    env_file: .env
    environment:
      API_URL: http://manager:8080/api
      API_SOCKET: /run/manager.sock
      DHCP_SERVER_IP_ADDR: 192.168.100.1
      DHCP_START_IP_ADDR: 192.168.100.2
      DHCP_LEASE_RANGE: 50
      DHCP_OPTIONS: |
        SubnetMask: 255.255.255.0
        Router:
          - 192.168.100.1
        DomainNameServer:
          - 8.8.8.8
          - 8.8.4.4
        DomainName: ztp.kstm.cloud
    ports:
      - 67:67/udp
    volumes:
      - ./tmp/run:/run:ro
  storage:
    image: kstm/ztp:storage
#   build: storage
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./tmp/moby:/tmp/moby
      - ./images:/images
    ports:
        - 3000
    environment:
      PORT: 3000
      API_URL: http://manager:8080/api
      OUTPUT_DIR: /images
      TEMPORARY_DIR: /tmp/moby
  tftp:
    image: kstm/ztp:tftp
#   build: tftp
    network_mode: host
    volumes:
      - ./images:/images:ro
